# NSS configuration — air-gap embedded device.
# `files` only: glibc consults /etc/hosts (and similar files) and never tries
# DNS. This is critical for air-gap reliability — without `nsswitch.conf` or
# with the default `dns` entry, every getaddrinfo() that fails the files
# lookup will block for ~30s waiting on DNS.
passwd:     files
group:      files
shadow:     files
gshadow:    files
hosts:      files
networks:   files
protocols:  files
services:   files
ethers:     files
rpc:        files
netgroup:   files
